/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Duuhh;

/**
 *
 * @author G-FORCE007
 */
public class Mondongo extends javax.swing.JFrame {

    public Double uno;
    public Double dos;
    public Double tres;
    public Double cuatro;
    public Double cinco;
    public Double seis;
    public Double siete;
    public Double ocho;
    public Double nueve;
    public String operador;
    
    
    public Mondongo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero_9 = new javax.swing.JButton();
        casilla = new javax.swing.JLabel();
        multiplicación = new javax.swing.JButton();
        numero_5 = new javax.swing.JButton();
        numero_6 = new javax.swing.JButton();
        numero_2 = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        numero_3 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        porcentaje = new javax.swing.JButton();
        borrar_todo = new javax.swing.JButton();
        borrar_uno = new javax.swing.JButton();
        division = new javax.swing.JButton();
        numero_7 = new javax.swing.JButton();
        numero_4 = new javax.swing.JButton();
        numero_1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        numero_8 = new javax.swing.JButton();
        resultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numero_9.setBackground(new java.awt.Color(255, 255, 255));
        numero_9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_9.setForeground(new java.awt.Color(0, 0, 0));
        numero_9.setText("9");
        numero_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_9ActionPerformed(evt);
            }
        });

        casilla.setBackground(new java.awt.Color(204, 204, 204));
        casilla.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        casilla.setForeground(new java.awt.Color(0, 0, 0));
        casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        multiplicación.setBackground(new java.awt.Color(204, 204, 204));
        multiplicación.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        multiplicación.setForeground(new java.awt.Color(0, 0, 0));
        multiplicación.setText("×");
        multiplicación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicaciónActionPerformed(evt);
            }
        });

        numero_5.setBackground(new java.awt.Color(255, 255, 255));
        numero_5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_5.setForeground(new java.awt.Color(0, 0, 0));
        numero_5.setText("5");
        numero_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_5ActionPerformed(evt);
            }
        });

        numero_6.setBackground(new java.awt.Color(255, 255, 255));
        numero_6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_6.setForeground(new java.awt.Color(0, 0, 0));
        numero_6.setText("6");
        numero_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_6ActionPerformed(evt);
            }
        });

        numero_2.setBackground(new java.awt.Color(255, 255, 255));
        numero_2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_2.setForeground(new java.awt.Color(0, 0, 0));
        numero_2.setText("2");
        numero_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_2ActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(255, 255, 255));
        cero.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        cero.setForeground(new java.awt.Color(0, 0, 0));
        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        numero_3.setBackground(new java.awt.Color(255, 255, 255));
        numero_3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_3.setForeground(new java.awt.Color(0, 0, 0));
        numero_3.setText("3");
        numero_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_3ActionPerformed(evt);
            }
        });

        punto.setBackground(new java.awt.Color(255, 255, 255));
        punto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        punto.setForeground(new java.awt.Color(0, 0, 0));
        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        suma.setBackground(new java.awt.Color(204, 204, 204));
        suma.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        suma.setForeground(new java.awt.Color(0, 0, 0));
        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        porcentaje.setBackground(new java.awt.Color(204, 204, 204));
        porcentaje.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        porcentaje.setForeground(new java.awt.Color(0, 0, 0));
        porcentaje.setText("%");
        porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeActionPerformed(evt);
            }
        });

        borrar_todo.setBackground(new java.awt.Color(204, 204, 204));
        borrar_todo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        borrar_todo.setForeground(new java.awt.Color(0, 0, 0));
        borrar_todo.setText("CE");
        borrar_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_todoActionPerformed(evt);
            }
        });

        borrar_uno.setBackground(new java.awt.Color(204, 204, 204));
        borrar_uno.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        borrar_uno.setForeground(new java.awt.Color(0, 0, 0));
        borrar_uno.setText("C");
        borrar_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_unoActionPerformed(evt);
            }
        });

        division.setBackground(new java.awt.Color(204, 204, 204));
        division.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        division.setForeground(new java.awt.Color(0, 0, 0));
        division.setText("÷");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        numero_7.setBackground(new java.awt.Color(255, 255, 255));
        numero_7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_7.setForeground(new java.awt.Color(0, 0, 0));
        numero_7.setText("7");
        numero_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_7ActionPerformed(evt);
            }
        });

        numero_4.setBackground(new java.awt.Color(255, 255, 255));
        numero_4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_4.setForeground(new java.awt.Color(0, 0, 0));
        numero_4.setText("4");
        numero_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_4ActionPerformed(evt);
            }
        });

        numero_1.setBackground(new java.awt.Color(255, 255, 255));
        numero_1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_1.setForeground(new java.awt.Color(0, 0, 0));
        numero_1.setText("1");
        numero_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_1ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("+/-");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        resta.setBackground(new java.awt.Color(204, 204, 204));
        resta.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        resta.setForeground(new java.awt.Color(0, 0, 0));
        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        numero_8.setBackground(new java.awt.Color(255, 255, 255));
        numero_8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        numero_8.setForeground(new java.awt.Color(0, 0, 0));
        numero_8.setText("8");
        numero_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_8ActionPerformed(evt);
            }
        });

        resultado.setBackground(new java.awt.Color(0, 51, 153));
        resultado.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setText("=");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numero_4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(numero_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(porcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numero_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numero_5, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(borrar_todo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(borrar_uno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(numero_9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numero_6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(numero_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(numero_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numero_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiplicación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrar_todo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrar_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(multiplicación, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero_7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero_8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(numero_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero_4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero_5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero_6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resta, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(numero_3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(punto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_9ActionPerformed
    this.casilla.setText(this.casilla.getText() + "9");        
    }//GEN-LAST:event_numero_9ActionPerformed

    private void multiplicaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicaciónActionPerformed
    this.uno = Double.parseDouble(this.casilla.getText());         
    this.operador = "×";
    this.casilla.setText("");        
    }//GEN-LAST:event_multiplicaciónActionPerformed

    private void numero_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_5ActionPerformed
    this.casilla.setText(this.casilla.getText() + "5");        
    }//GEN-LAST:event_numero_5ActionPerformed

    private void numero_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_6ActionPerformed
    this.casilla.setText(this.casilla.getText() + "6");       
    }//GEN-LAST:event_numero_6ActionPerformed

    private void numero_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_2ActionPerformed
    this.casilla.setText(this.casilla.getText() + "2");
    }//GEN-LAST:event_numero_2ActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        this.casilla.setText(this.casilla.getText() + "0");
    }//GEN-LAST:event_ceroActionPerformed

    private void numero_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_3ActionPerformed
    this.casilla.setText(this.casilla.getText() + "3");       
    }//GEN-LAST:event_numero_3ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
    this.casilla.setText(this.casilla.getText() + ".");  
    }//GEN-LAST:event_puntoActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
    this.uno = Double.parseDouble(this.casilla.getText());         
    this.operador = "+";
    this.casilla.setText("");
    }//GEN-LAST:event_sumaActionPerformed

    private void porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_porcentajeActionPerformed

    private void borrar_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_todoActionPerformed
    this.casilla.setText("");       
    }//GEN-LAST:event_borrar_todoActionPerformed

    private void borrar_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_unoActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_borrar_unoActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
    this.uno = Double.parseDouble(this.casilla.getText());         
    this.operador = "÷";
    this.casilla.setText("");      
    }//GEN-LAST:event_divisionActionPerformed

    private void numero_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_7ActionPerformed
    this.casilla.setText(this.casilla.getText() + "7");        
    }//GEN-LAST:event_numero_7ActionPerformed

    private void numero_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_4ActionPerformed
    this.casilla.setText(this.casilla.getText() + "4");        
    }//GEN-LAST:event_numero_4ActionPerformed

    private void numero_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_1ActionPerformed
        this.casilla.setText(this.casilla.getText() + "1");
    }//GEN-LAST:event_numero_1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
    this.uno = Double.parseDouble(this.casilla.getText());         
    this.operador = "-";
    this.casilla.setText("");
    }//GEN-LAST:event_restaActionPerformed

    private void numero_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_8ActionPerformed
    this.casilla.setText(this.casilla.getText() + "8");        
    }//GEN-LAST:event_numero_8ActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
    this.dos = Double.parseDouble(this.casilla.getText());
    //this.tres = Double.parseDouble(this.casilla.getText());

    if (this.operador.equals("+")){
        this.casilla.setText(Double.toString(this.uno + this.dos));
    } else if (this.operador.equals("-")){
        this.casilla.setText(Double.toString(this.uno - this.dos));
    } else if (this.operador.equals("÷")){
        this.casilla.setText(Double.toString(this.uno / this.dos));
    } else if (this.operador.equals("×")){
        this.casilla.setText(Double.toString(this.uno * this.dos));
    }          
    }//GEN-LAST:event_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mondongo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mondongo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mondongo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mondongo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mondongo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar_todo;
    private javax.swing.JButton borrar_uno;
    private javax.swing.JLabel casilla;
    private javax.swing.JButton cero;
    private javax.swing.JButton division;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton multiplicación;
    private javax.swing.JButton numero_1;
    private javax.swing.JButton numero_2;
    private javax.swing.JButton numero_3;
    private javax.swing.JButton numero_4;
    private javax.swing.JButton numero_5;
    private javax.swing.JButton numero_6;
    private javax.swing.JButton numero_7;
    private javax.swing.JButton numero_8;
    private javax.swing.JButton numero_9;
    private javax.swing.JButton porcentaje;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton resultado;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
